sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
- bundle -v
- rm Gemfile.lock || true
- gem update --system
- gem update bundler
- gem --version
- bundle -v
script:
- bundle exec rake $CHECK
bundler_args: "--without system_tests"
rvm:
- 2.3.1
- 2.1.7
env:
- PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
matrix:
  fast_finish: true
  include:
  - env: CHECK=rubocop
  - env: CHECK="syntax lint"
  - env: CHECK=metadata_lint
branches:
  only:
  - master
  - "/^v\\d/"
notifications:
  email: false
  pushover:
    api_key:
      secure: '08fVLSFcs8TyqbszsyEjgZXVwYiIWyt+NAFSVRGvFxQvBMTB+EMhNNnAoOfZv211AWkvDM5pHYVAL4NWO2khD0bkJ6ntJbgLcAusloqe+GzyKBfqxz40DI5vde2RGf1P9khHoA4Qa+QVyztVP6E+kMtqYrqkBkhRZdxTPrvP+0DSz9cvfirKajuMn5hDl3jDuoeJqyUXL5X0vKvZDNTShEMmCxW6l4KkueRGKxERfuVCZ0gTqqHP21ZW4EWPcfIxeAWvCL97J57mxD2TEb04aNv8YQbciJmG01S4eu78xMI5lSiSP/f7SNjo0GgIKcCPXY4Ma4jCMEWHu54DjXW4gg4G+aIiP2P1BF39jjbBJVkcYUFuf8RSSe6OH+/hhObZcP1Wuu8Mix6PVL3wH+EsnpHp1aEY2w0m6/Zq348NHrITS+BK4wdZR30+FxaE3qxCFu+5vpNS/qoByE7dCq3xGrI/5FSFNQ0Eavqh/Z3cHwNXUw8So2d+3NVzIuoy29N3hcpG9nQpUy+K6ac43R7UtMYOnlWfkZJQS+qerD8p3t31UxKls1/WPzOAeGlqMKz4mK/l2X5KgsIP/UYPilGwIqqWiiXUAtUDWQ3Ymv5vHo+od9Qhn3UTLQvssMFlUBJnZwAK/avIxeYdQnJ1GCuv9tdQdR3O0naE638AgY8D6IM='
    users:
      secure: qYaSacidOrg1wKsvwfAdgePg7OWPCMo2PWmcighpOZ9M2M6q2yeB4UpEQi9lo/L45xkN2gVqME/G8Iofhr7EWUALajQzXFoGBfjNobV+8Aj9GYkjdpJF5Z88bHV6847P1XAkQ0n9SjaQLcJ77Ks/J3ZHh3tMQxAARVHjvIo17UCfNZs2fCPvE4vvnc2qzvc2iBPbGgTI6jXKZuSweIrzG3liqKh3b+S6gMTBS3dJhN3Pvnxd+uhrvfiU9+5zsZt2UyHi8XOihkjKQIpOWQyl798y6QqNdvryzvoLngxY4Ot1XAFEQTgsSCp9E/kexTs8p9pIGs7/7eO6xj2hlPXeNke9pO7+rPXFyCqa1LcgKf3yrdOHzj0rAuJ+D0nKiYtJRehtohCptZ0BwF2h1PScURBFagjwO0i8o4T47omEfrwrSn/85WBveumCqntY0IkqRPQpYAB70VLkWssv/Oh5QTlYVK+G6zC4qhx0SE7zMU12aL0E9Wl0JUsxoVqizGDlVvaaPaYBtLpMSsJ1bThNTUvrFsuxLK1YlpIdxhgXux1r2nxmr9S0W4UwQGGyBpjpIXs9QdEBmzpi9rG6RPqSYG1wqGoKUTQBplD7NznzyDkRt7tsWSBrRRJia1XL0c4mBuAs2cfgO6NKtYsXk5O0+rjVOr1FIxIcQqcbEsKL1Cg=
deploy:
  provider: puppetforge
  user: zerodecimal
  password:
    secure: ZmDVedTD/Nrf7miAVn+1jAzlJPh0CtlDRueM57ziyeijN7vfI0w8XoHpRsXQRMVEMPyqfL6uhBSad9+0ee44dXHI8E1/HHfp7P6M9LAFJ5bjAXj+eaYelA8hkWXC5u/74HQBkLR1svkCHeZFN/YtoY2bNH9owKWJDfyoys2I8/Sn4aATqi0i3134sHFyn7eKASNNsUVaU7Zv1p+3WciUEDut46LlblFJrVDqgLpHFFV41ey9JCRb23JhqmmK34BleHUDVD5wPgBEku7zQA2Idg7Nvg9MSB6qr/xQCOF3D6cnv+5Oy7eh4EdZwyGSiHSrhKfjqxx2HUZy/LHQh5K85/XA2JjX+2heILfc+GGHRYseq/E7XMrDJlozeuUMqgSg9OiyITplIEHxEWwgDMRQFO3zIuxR7TH5uk9L+PhGDk0P25ikyzdyUYFTZI/n054PSdEyAgdnbZS7n/f2zM9xRVyRCkBrJPxIyM+AE4T2ywjNCWjsJjeR2JWDu9T1YOVgSSlNd9Sq+nrUKGzCAHN9U9necOdxs0nna8boQbPnL75vqcG+132cmEYHxvLmwE/g2Y9LID0JR8lMZFbljFqUx5KKJ646SsQlsE37t3/f1DnGJZmtR8erOawiqJjXljWCYflSVIbN0xW8mVZlIWuxa0QvcIhlsLAVG/3GsMxdbWU=
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
